name: Scorpion Remote Engine
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Reconstruct Project On Server
        run: |
          # هنا السيرفر هيخلق مجلد الأندرويد الرسمي اللي مش موجود عندك
          flutter create . --platforms android --org com.adham.mirror
          flutter pub get

      - name: Build Secure APK
        run: flutter build apk --debug
          
      - name: Export Scorpion APK
        uses: actions/upload-artifact@v4
        with:
          name: Mirror-Scorpion2-Final
          path: build/app/outputs/flutter-apk/app-debug.apk
