name: Scorpion Remote Engine
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Final Surgical Fix
        run: |
          rm -rf android build .dart_tool
          flutter create . --project-name mirror_scorpion2 --org com.adham.mirror
          
          # إعدادات الـ SDK لعام 2026
          sed -i 's/compileSdk = .*/compileSdk = 36/g' android/app/build.gradle.kts
          sed -i 's/minSdk = .*/minSdk = 24/g' android/app/build.gradle.kts
          
          # تفعيل خاصية Desugaring في خيارات الكومبايلر (الحل الجذري)
          sed -i '/compileOptions {/a \        isCoreLibraryDesugaringEnabled = true' android/app/build.gradle.kts
          
          # إضافة المكتبة المطلوبة تحت بند الـ dependencies
          sed -i '/dependencies {/a \    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")' android/app/build.gradle.kts
          
          flutter pub get
          
      - name: Build Secure APK
        run: flutter build apk --debug
          
      - name: Export Scorpion APK
        uses: actions/upload-artifact@v4
        with:
          name: Mirror-Scorpion2-Final
          path: build/app/outputs/flutter-apk/app-debug.apk
